import Foundation

// Stable identifier used for both the macOS LaunchAgent label and Nix-managed defaults suite.
// nix-nanosolana writes app defaults into this suite to survive app bundle identifier churn.
let launchdLabel = "ai.nanosolana.mac"
let gatewayLaunchdLabel = "ai.nanosolana.gateway"
let onboardingVersionKey = "nanosolana.onboardingVersion"
let onboardingSeenKey = "nanosolana.onboardingSeen"
let currentOnboardingVersion = 7
let pauseDefaultsKey = "nanosolana.pauseEnabled"
let iconAnimationsEnabledKey = "nanosolana.iconAnimationsEnabled"
let swabbleEnabledKey = "nanosolana.swabbleEnabled"
let swabbleTriggersKey = "nanosolana.swabbleTriggers"
let voiceWakeTriggerChimeKey = "nanosolana.voiceWakeTriggerChime"
let voiceWakeSendChimeKey = "nanosolana.voiceWakeSendChime"
let showDockIconKey = "nanosolana.showDockIcon"
let defaultVoiceWakeTriggers = ["nanosolana"]
let voiceWakeMaxWords = 32
let voiceWakeMaxWordLength = 64
let voiceWakeMicKey = "nanosolana.voiceWakeMicID"
let voiceWakeMicNameKey = "nanosolana.voiceWakeMicName"
let voiceWakeLocaleKey = "nanosolana.voiceWakeLocaleID"
let voiceWakeAdditionalLocalesKey = "nanosolana.voiceWakeAdditionalLocaleIDs"
let voicePushToTalkEnabledKey = "nanosolana.voicePushToTalkEnabled"
let talkEnabledKey = "nanosolana.talkEnabled"
let iconOverrideKey = "nanosolana.iconOverride"
let connectionModeKey = "nanosolana.connectionMode"
let remoteTargetKey = "nanosolana.remoteTarget"
let remoteIdentityKey = "nanosolana.remoteIdentity"
let remoteProjectRootKey = "nanosolana.remoteProjectRoot"
let remoteCliPathKey = "nanosolana.remoteCliPath"
let nanoSolanaGatewayURLKey = "nanosolana.nanoSolana.gatewayUrl"
let nanoSolanaGatewaySecretKey = "nanosolana.nanoSolana.gatewaySecret"
let nanoSolanaDefaultGatewayURL = "http://127.0.0.1:18790"
let canvasEnabledKey = "nanosolana.canvasEnabled"
let cameraEnabledKey = "nanosolana.cameraEnabled"
let systemRunPolicyKey = "nanosolana.systemRunPolicy"
let systemRunAllowlistKey = "nanosolana.systemRunAllowlist"
let systemRunEnabledKey = "nanosolana.systemRunEnabled"
let locationModeKey = "nanosolana.locationMode"
let locationPreciseKey = "nanosolana.locationPreciseEnabled"
let peekabooBridgeEnabledKey = "nanosolana.peekabooBridgeEnabled"
let deepLinkKeyKey = "nanosolana.deepLinkKey"
let modelCatalogPathKey = "nanosolana.modelCatalogPath"
let modelCatalogReloadKey = "nanosolana.modelCatalogReload"
let cliInstallPromptedVersionKey = "nanosolana.cliInstallPromptedVersion"
let heartbeatsEnabledKey = "nanosolana.heartbeatsEnabled"
let debugPaneEnabledKey = "nanosolana.debugPaneEnabled"
let debugFileLogEnabledKey = "nanosolana.debug.fileLogEnabled"
let appLogLevelKey = "nanosolana.debug.appLogLevel"
let voiceWakeSupported: Bool = ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 26
